server:
  port: 80
mybatis:
  mapper-locations: classpath:mappers/*xml

spring:
  rabbitmq:
    host: u.huangsikai.top
    port: 15672
    username: admin
    password: 31eea5e3
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://u.huangsikai.top:3306/event_res?useSSL=false&serverTimezone=UTC
    username: event_res
    password: hsk040722
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 20
      max-wait: 5000
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
