server:
  port: 80
mybatis:
  mapper-locations: classpath:mappers/*xml


mail:
  configs:
    # 账号
    - username: iotclub2@email.cn
      password: YTrkHRbytKJ8VNs2
      host: smtp.email.cn
      port: 465
      protocol: smtps
      default-encoding: UTF-8
    # 账号A
    - username: iotclub3@email.cn
      password: TMW8QBBAU9EPicnT
      host: smtp.email.cn
      port: 465
      protocol: smtps
      default-encoding: UTF-8

    # 账号A
    - username: iotclub6@email.cn
      password: yaANiKVX3EPH8cQh
      host: smtp.email.cn
      port: 465
      protocol: smtps
      default-encoding: UTF-8
    # 账号A
    - username: iotclub7@email.cn
      password: Ry7iVg4JRYzxT2SR
      host: smtp.email.cn
      port: 465
      protocol: smtps
      default-encoding: UTF-8

    - username: iotclub4@163.com
      password: TALSEEOOCGUYYCDX
      host: smtp.163.com
      port: 465
      protocol: smtps
      default-encoding: UTF-8

    - username: iotclub5@163.com
      password: WGJSEKIJRPCOKPWN
      host: smtp.163.com
      port: 465
      protocol: smtps
      default-encoding: UTF-8

    - username: iotclub@email.cn
      password: XsRSp8xSd36RNqpd
      host: smtp.email.cn
      port: 465
      protocol: smtps
      default-encoding: UTF-8


spring:
  mail:
    properties:
      mail:
        debug: true #启动debug调试
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory #SSL连接配置
  rabbitmq:
    host: u.huangsikai.top
    port: 5672
    username: admin
    password: 31eea5e3
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://u.huangsikai.top:3306/event_res?useSSL=false&serverTimezone=UTC
    username: event_res
    password: hsk040722
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 20
      max-wait: 5000
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
  data:
    redis:
      host: u.huangsikai.top
      password: hsk040722
      port: 6379
      connect-timeout: 30000ms
      lettuce:
        pool:
          max-active: 10
          max-wait: 60000ms
          max-idle: 8
          min-idle: 0
config:
  jwt:
    secret: hsk_code
    expire: 1800
    header: token



